### ISSUE TITLE
Custom text on LCD

### ISSUE THREAD

**Issue by lmateovf** [mafredri/lcm#2]
Hi,
First of all, thank you for making this software, I was able to turn off the LCD and now i don't have to worry about that bright light but...
Is there anyway to display the ip or the name?
If so, how?
My setup is:
-  AS6404T
- Ubuntu server (22.04)

Thank you in advance and please excuse my english if it's too bad haha (not my native language)

**Comment by mafredri** [comment]
Are you using openlcmd? Do you not see hostname and IP if you press one of the lcd buttons to wake it up?

**Comment by lmateovf** [comment]
Ooh, I'm so sorry, it actually works... I pressed one of the LCD and it woke up, i'm so sorry hahaha
thanks again for this great software

**Comment by mafredri** [comment]
Haha, that's great. Glad you like it! ☺️
